Set-Location "C:\Projects\Billigkurven"
if (Test-Path Env:LIVE_PRICING_MAX_PRODUCTS) { Remove-Item Env:LIVE_PRICING_MAX_PRODUCTS }
$env:LIVE_PRICING_MIN_INTERVAL_HOURS = "6"
$env:LIVE_PRICING_ENABLE_CATALOG_DISCOVERY = "true"
$env:LIVE_PRICING_DISCOVERY_MAX_CANDIDATES_PER_PROVIDER = "8000"
$env:LIVE_PRICING_ODA_SEARCH_PAGES = "80"
$env:LIVE_PRICING_NG_SEARCH_PAGES = "80"
$env:LIVE_PRICING_NG_PAGE_SIZE = "250"
npm run prices:sync